### PR TITLE
Update info.rkt to fix build failure.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by samth** [comment]
Ping.

**Comment by LawrenceWoodman** [comment]
@samth I have moved away from Racket for the moment, so although this is a simple change I can't test it.  I'm happy to give you commit rights on the repo if you would like; let me know.

**Comment by samth** [comment]
I've tested this, so if you just merge this that would be great. You can
also see the build results on pkg-build.racket-lang.org.

Sam

**Comment by lawrencewoodman** [comment]
It's been a long wait, sorry.  Merged request now.

**Pull request closed without merging**
